name: Scheduled Repo Sync

on:
  schedule:
    - cron: '0 0 * * *' # Täglich um 00:00 Uhr
  workflow_dispatch: # Ermöglicht manuellen Start über das UI

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream
    
    permissions:
      contents: write

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        ref: main
        # Das GITHUB_TOKEN reicht aus, da wir oben Schreibrechte (permissions) vergeben haben.
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Sync Upstream
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_repo: derlemue/villa-kunterbunt
        upstream_sync_branch: main
        target_sync_branch: main
        test_mode: false
