name: Sync Fork Caller

on:
  schedule:
    - cron: '00 */2 * * *'
  workflow_dispatch:

# Wir definieren die Permissions hier global...
permissions:
  contents: write

jobs:
  call-sync-fork:
    # ...und stellen sicher, dass der Job sie auch wirklich anwenden darf
    permissions:
      contents: write
    uses: lemueIO/.github/.github/workflows/central-sync-logic.yml@main
    with:
      upstream_url: "https://github.com/derlemue/villa-kunterbunt.git"
    secrets: inherit
