name: Fork Sync Caller

on:
  schedule:
    - cron: '*/30 * * * *' # Alle 30 Minuten
  workflow_dispatch:      # Erm√∂glicht manuellen Start

jobs:
  sync:
    uses: lemueIO/.github/.github/workflows/central-sync-logic.yml@main
    with:
      upstream_url: "https://github.com/derlemue/villa-kunterbunt.git"
    secrets: inherit
